runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /(.*\.(js))$
  static_files: js/\1
  upload: /.*\.(gif|png|jpg)$
  
- url: /auth
  script: _go_app

- url: /worker/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
  login: required
  auth_fail_action: redirect